app/models/user.py
from app.extensions import db
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from .sqlalchemy_helpers import DefaultUserMixin


class User(db.Model, DefaultUserMixin):
    __tablename__ = 'users'

    id = db.Column(db.Integer(), primary_key=True)
    username = db.Column(db.String(50), unique=True)  # TODO: lower limit to 15
    email = db.Column(db.String(255), unique=True)

    # for oauth providers that don't guarantee user's email (GitHub)
    oauthId = db.Column(db.String(50))
    oauthProvider = db.Column(db.String(50))

    firstName = db.Column(db.String(50))
    lastName = db.Column(db.String(50))

    pwdhash = db.Column(db.String(255))

    avatar = db.Column(db.String(255), default='avatar.jpg')
    dateJoined = db.Column(db.DateTime(), default=datetime.utcnow)

    isAdmin = db.Column(db.Boolean(), default=False)

    articles = db.relationship('Article', backref='author', lazy='dynamic')

    comments = db.relationship('Comment', backref='user', lazy='dynamic')

    def __init__(self, **kwargs):
        super(User, self).__init__(**kwargs)
        self.pwdhash = generate_password_hash(self.pwdhash)

    def check_password(self, password):
        return check_password_hash(self.pwdhash, password)

app/forms/user.py
import os
import imghdr
import json
import pprint
from app.forms.wtf_custom_fields import strip_filter, HiddenInteger

from app.models import User, Category

from wtforms import ValidationError, StringField, FileField, HiddenField, TextAreaField, PasswordField
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from wtforms.validators import InputRequired, Length, Email
from werkzeug.datastructures import FileStorage

from flask import session, current_app
from flask_wtf import Form
from flask_login import current_user


# Article Forms
class AddArticleForm(Form):
    title = StringField('Title', validators=[InputRequired(), Length(min=1, max=250)])
    category = QuerySelectField('Category', query_factory=lambda: Category.query.all(), validators=[InputRequired()])
    body = TextAreaField('Body', validators=[InputRequired()])


class EditArticleForm(AddArticleForm):
    id = HiddenInteger('id', validators=[InputRequired()])


class DeleteArticleForm(Form):
    id = HiddenInteger('id', validators=[InputRequired()])


# Category Forms
class AddCategoryForm(Form):
    name = StringField('Category', validators=[InputRequired(), Length(min=1)], filters=[strip_filter])

    def validate_name(self, field):
        if Category.query.filter_by(name_insensitive=field.data).first():
            raise ValidationError('This category already exists')


class EditCategoryForm(Form):
    id = HiddenInteger('id', validators=[InputRequired()])
    category = QuerySelectField('Choose Category', query_factory=lambda: Category.query.all())
    name = StringField('Name', validators=[InputRequired(), Length(min=1)], filters=[strip_filter])

    def validate_name(self, field):
        if Category.query.filter_by(name_insensitive=field.data).first():
            raise ValidationError('This category already exists')


class DeleteCategoryForm(Form):
    category = QuerySelectField('Category', query_factory=lambda: Category.query.all(), validators=[InputRequired()])
    id = HiddenInteger('id', validators=[InputRequired()])


# Profile Form
class EditProfileForm(Form):
    id = HiddenInteger('id', validators=[InputRequired()])
    username = StringField('Username', validators=[InputRequired()])
    email = StringField('Email', validators=[InputRequired(), Email()])
    firstName = StringField('First Name', validators=[InputRequired()])
    lastName = StringField('Last Name', validators=[InputRequired()])

    def validate_username(self, field):
        if field.data != current_user.username and not current_user.is_admin():
            raise ValidationError('You do not have permission to change your username.')

        existing_user = User.query.filter_by(username_insensitive=field.data).first()
        if existing_user and existing_user.id != self.id.data:
            raise ValidationError('Sorry this username is taken... please choose another.')


class DeleteUserForm(Form):
    id = HiddenInteger('id', validators=[InputRequired()])


# Avatar Form
class UploadAvatarForm(Form):
    cropData = HiddenField('cropData')
    avatar = FileField('Upload Image')

    def validate_avatar(self, field):
        fileStorage = field.data

        # if no file was provided we will use the original image
        if not isinstance(fileStorage, FileStorage):
            return

        # check the data signature for a valid image
        extension = imghdr.what(fileStorage)
        if extension not in current_app.config.get('ALLOWED_EXTENSIONS', ('',)):
            raise ValidationError('Only images are allowed...')

        # check file size
        fileStorage.seek(0, os.SEEK_END)
        size = fileStorage.tell()
        if size == 0:
            raise ValidationError("You can't upload an empty file.")
        fileStorage.seek(0, os.SEEK_SET)  # reset file pointer

        maxByteSize = current_app.config['MAX_UPLOAD_SIZE']
        if size > maxByteSize:
            raise ValidationError(
                'File size is too large... please choose an image smaller than ' + str(int(maxByteSize / 1024)) + ' KB')

    def validate_cropData(self, field):
        print 'field.data = ', field.data
        try:
            data = json.loads(field.data)
            pprint.pprint(data)
            data = {
                'x': int(data['x']),
                'y': int(data['y']),
                'width': int(data['width']),
                'height': int(data['height'])
            }

        except Exception, e:
            print e
            raise ValueError('Invalid json data.')

        field.data = data

app/schemas/user/__init__.py
from profile_view import ProfileViewSchema

app/views/user.py
import os
from PIL import Image
from shutil import copyfile

from flask import Blueprint, render_template, request, flash, session, current_app, url_for
from flask_login import current_user, login_required
from sqlalchemy import func

from app.extensions import db
from app.models import User, Article
from app.utils import xhr_required, get_login_manager_data, xhr_or_template
from app.models import Category, Article
from app.schemas import user_profile_view_serializer as profile_view_serializer, user_info_serializer
from app.forms import (
    AddArticleForm, EditArticleForm, DeleteArticleForm,
    AddCategoryForm, EditCategoryForm, DeleteCategoryForm,
    EditProfileForm, UploadAvatarForm,
    DeleteUserForm
)

user_bp = Blueprint('user', __name__, url_prefix='/user')


@user_bp.route('/profile/')
@login_required
@xhr_or_template('user/profile.html')
def profile():
    # Create response using `ProfileViewSchema`
    result = profile_view_serializer.dump({
        'user': current_user,
        'articles': Article.query.filter_by(authorId=current_user.id).order_by(func.lower(Article.title)).all(),
        'navbar': {
            'categories': Category.query.order_by(Category.name).all()
        }
    }).data

    return {'status': 200, 'result': result}

@user_bp.route('/profile/edit', methods=['POST'])
@xhr_required
def edit_profile():
    form = EditProfileForm(request.form)
    if form.validate_on_submit():
        # prevent non admin users from editing other users profile
        if not current_user.is_admin():
            form.id.data = current_user.id
        user = User.query.get(form.id.data)
        user.populate_from_form(form)
        db.session.commit()
        flash('Successfully updated user info.', 'success')
        return {'status': 200}
    else:
        flash(form.errors, 'form-error')
        return {'status': 400}

@user_bp.route('/profile/articles/add', methods=['POST'])
@xhr_required
def add_article():
    form = AddArticleForm(request.form)
    if form.validate_on_submit():
        article = Article(authorId=current_user.id, **form.data)
        db.session.add(article)
        db.session.commit()
        flash("Successfully published <strong>'" + article.title + "'</strong>.", 'success')
        return {'status': 200}
    else:
        flash(form.errors, 'form-error')
        return {'status': 400}

@user_bp.route('/profile/articles/edit', methods=['POST'])
@login_required
@xhr_required
def edit_article():
    form = EditArticleForm(request.form)
    if form.validate_on_submit():
        article = Article.query.get(form.id.data)
        # ensure user has permission to edit this article
        if article.authorId == current_user.id or current_user.is_admin():
            article.populate_from_form(form)
            db.session.commit()
            flash("Successfully updated <strong>'" + article.title + "'</strong> article.", 'success')
            return {'status': 200}
        else:
            flash('You do not have permission to edit <strong>' + article.title + '</strong>. article', 'danger')
            return {'status': 403}
    else:
        flash(form.errors, 'form-error')
        return {'status': 400}

@user_bp.route('/profile/articles/delete', methods=['POST'])
@xhr_required
def delete_article():
    form = DeleteArticleForm(request.form)
    if form.validate_on_submit():
        article = Article.query.get(form.id.data)
        if not article:
            flash("This articles doesn't exist...", 'danger')
            return {'status': 400}
        # ensure the user has ownership before deleting the article
        if current_user.id == article.authorId or current_user.is_admin():
            db.session.delete(article)
            db.session.commit()
            flash("Successfully deleted <strong>'" + article.title + "'</strong> article.", 'success')
            return {'status': 200}
        else:
            flash('You do not have permission to delete <strong>' + article.title + '</strong>.', 'danger')
            return {'status': 403}
    else:
        flash(form.errors, 'form-error')
        return {'status': 400}

@user_bp.route('/profile/categories/add', methods=['POST'])
@xhr_required
def add_category():
    if not current_user.is_admin():
        flash('Permission denied...', 'danger')
        return {'status': 403}

    form = AddCategoryForm(request.form)
    if form.validate_on_submit():
        category = Category(**form.data)
        db.session.add(category)
        db.session.commit()
        flash('Successfully added ' + category.name + '.', 'success')
        # return the updated navbar
        result = profile_view_serializer.dump({
            'navbar': {
                'categories': Category.query.order_by(Category.name).all()
            }
        }).data
        return {'status': 200, 'result': result}
    else:
        flash(form.errors, 'form-error')
        return {'status': 400}

@user_bp.route('/profile/categories/edit', methods=['POST'])
@xhr_required
def edit_category():
    if not current_user.is_admin():
        flash('Permission denied...', 'danger')
        return {'status': 403}

    form = EditCategoryForm(request.form)
    if form.validate_on_submit():
        category = Category.query.get(form.id.data)
        if not category:
            flash("This category doesn't exist...", 'danger')
            return {'status': 400}

        category.name = form.name.data
        db.session.commit()
        flash('Successfully updated ' + category.name + '.', 'success')
        # return the updated navbar
        result = profile_view_serializer.dump({
            'navbar': {
                'categories': Category.query.order_by(Category.name).all()
            }
        }).data
        return {'status': 200, 'result': result}
    else:
        flash(form.errors, 'form-error')
        return {'status': 400}

@user_bp.route('/profile/categories/delete', methods=['POST'])
@xhr_required
def delete_category():
    if not current_user.is_admin():
        flash('Permission denied...', 'danger')
        return {'status': 403}

    form = DeleteCategoryForm(request.form)

    if form.validate_on_submit():
        category = Category.query.get(form.id.data)
        if category.articles.first():
            flash("You can't delete a category containing articles.", 'danger')
            return {'status': 400}
        name = category.name
        db.session.delete(category)
        db.session.commit()
        flash('Successfully deleted ' + name, 'success')
        # return the updated navbar
        result = profile_view_serializer.dump({
            'navbar': {
                'categories': Category.query.order_by(func.lower(Category.name)).all()
            }
        }).data
        return {'status': 200, 'result': result}
    else:
        flash(form.errors, 'form-error')
        return {'status': 400}


@user_bp.route('/upload/avatar', methods=['POST'])
@xhr_required
def upload():
    form = UploadAvatarForm()
    if form.validate_on_submit():
        image = form.avatar.data
        # avatar folder directory
        path = os.path.join(current_app.config['UPLOAD_FOLDER'], 'avatar')
        # crop the provided image
        if image:
            # get the file extension.
            # Note: file extension was checked on form validation
            s = image.filename.rsplit('.', 1)

            # append user's id to filename
            filename = 'avatar-' + str(current_user.id) + '.' + s[1]
            # filename = secure_filename(filename)

            # get the paths used in `crop_image()`
            originalPath = os.path.join(path, 'original-' + filename)
            croppedPath = os.path.join(path, filename)

            # save the original image
            image.save(originalPath)
            image.close()
        else:
            # since no image was provided we will use the original image
            filename = current_user.avatar

            # create a file namespace if this is the user's first time editing his avatar
            if filename == 'avatar.jpg':
                filename = 'avatar-' + str(current_user.id) + '.jpg'
                copyfile(os.path.join(path, 'avatar.jpg'), os.path.join(path, filename))
                copyfile(os.path.join(path, 'original-avatar.jpg'), os.path.join(path, 'original-' + filename))

            # get the paths used in `crop_image()`
            originalPath = os.path.join(path, 'original-' + filename)
            croppedPath = os.path.join(path, filename)

        # create the cropped image
        crop_image(originalPath, croppedPath, form.cropData.data)

        # update user avatar path
        current_user.avatar = filename
        db.session.commit()
        flash('Successfully uploaded avatar image.', 'success')

        # return the new user avatar
        result = profile_view_serializer.dump({
            'user': current_user
        }).data

        return {'status': 200, 'result': result}
    else:
        flash(form.errors, 'form-error')
        return {'status': 400}


def crop_image(src, dst, size):
    original = Image.open(src)
    left = size['x']
    upper = size['y']
    right = left + size['width']
    lower = upper + size['height']
    cropped = original.crop((left, upper, right, lower))

    cropped.save(dst)
    cropped.close()

@user_bp.route('/profile/users/delete', methods=['POST'])
@xhr_required
def delete_user():
    if not current_user.is_admin():
        flash('Permission denied...', 'danger')
        return {'status': 403}
    form = DeleteUserForm(request.form)
    if form.validate_on_submit():
        if form.id.data == current_user.id:
            flash("You can't delete yourself. Find another admin user to do this for you.", 'danger')
            return {'status': 400}
        user = User.query.get(form.id.data)
        if not user:
            flash('Failed to delete non-existing user.')
            return {'status': 400}
        if user.articles.first():

app/templates/user/profile-templates.html
{% from 'macros/form-components.html' import render_form, render_form %}

{# START: Add/Edit/Delete Article forms #}
{% set defaultCategorySelect = {'data-bind': "options: categories, optionsText: 'name', optionsValue: 'id', value: selectedCategoryId"} %}
<script id="template-addArticle" type="template">
    {{ render_form(get_form('AddArticle'), { '_action': url_for('user.add_article'), 'category': defaultCategorySelect, 'body': {'rows': 6, 'cols':30} }, default_databind=false) }}
</script>
<script id="template-editArticle" type="template">
    {{ render_form(get_form('EditArticle'), { '_action': url_for('user.edit_article'), 'category': defaultCategorySelect, 'body': {'rows': 6, 'cols':30} }) }}
</script>
<script id="template-deleteArticle" type="template">
    <p>Are you sure you want to delete <strong class="text-danger-inverse" data-bind="text: articleTitle"></strong> permanently?</p>
    {{ render_form(get_form('DeleteArticle'), { '_action': url_for('user.delete_article') }) }}
</script>
{# END: Add/Edit/Delete Article forms #}


{# START: Article table #}
<script id="template-articleTable" type="text/html">
    <table class="table-articles">
        <thead data-bind="sortTable: { list: articles }">
            <tr>
                <th data-sort-by="title">Title</th>
                <th data-sort-by="category.id">Category</th>
                <th data-sort-by="dateCreated">Date Created</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody data-bind="foreach: articles">
            <tr>
                <td class="title">
                    <a href="" data-bind="text: title, attr: { href: url }"></a>
                </td>
                <td class="category" data-bind="text: category.name"></td>
                <td class="date" data-bind="timeFromNow: dateCreated"></td>
                <td class="action">
                    <a data-bind="click: $parent.modal.editArticle" class="btn btn-sm btn-warning">Edit</a>
                    <a data-bind="click: $parent.modal.deleteArticle" class="btn btn-sm btn-danger">Delete</a>
                </td>
            </tr>
        </tbody>
        <tfoot data-bind="if: articles().length == 0">
            <tr>
                <td colspan="4" class="text-center" data-bind="text: emptyTableText"></td>
            </tr>
        </tfoot>
    </table>
</script>
{# END: Article table #}

{# START: Admin options menu #}
<script id="template-adminOptions" type="text/html">
    <div class="row row-table-sm">
        <div class="col-xs-12 text-center">
            <h1>Admin Options</h1>
            <a data-bind="click: toggleUserTable, text: btnUserTableText" class="btn btn-primary"></a>
            <a data-bind="click: categoryModal.addCategory, text: btnCategoryText" class="btn btn-primary"></a>
        </div>
    </div>
    <!-- ko if: userTable.isVisible -->
    <div class="row row-table-sm">
        <div class="col-xs-12">
            <h1 class="main-title">Registered Users</h1>
        </div>
    </div>
    <table data-bind="with: userTable" class="table-articles">
        <thead>
            <tr>
                <th>id</th>
                <th>Username</th>
                <th>Articles</th>
                <th>Date Joined</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody data-bind="foreach: users">
            <tr>
                <td data-bind="text: id"></td>
                <td data-bind="text: username"></td>
                <td><a data-bind="click: $root.admin.showArticlesByUserID" href="#">view articles</a></td>
                <td data-bind="timeFromNow: dateJoined"></td>
                <td class="action">
                    <a data-bind="click: $parent.modal.editUser" class="btn btn-sm btn-warning">Edit</a>
                    <a data-bind="click: $parent.modal.deleteUser" class="btn btn-sm btn-danger">Delete</a>
                </td>
            </tr>
        </tbody>
        <tfoot data-bind="if: users().length == 0">
            <tr>
                <td colspan="5" class="text-center" data-bind="text: emptyTableText"></td>
            </tr>
        </tfoot>
    </table>
    <!-- /ko-->
    <!-- ko if: articleTable.isVisible -->
    <div class="row row-table-sm">
        <div class="col-xs-12 col-sm-8">
            <h1 class="main-title" data-bind="text: articleTableTitle"></h1>
        </div>
        <div class="col-xs-12 col-sm-4 add-btn-container">
            {# `showUserTable.bind($data, true)` is required to use table cache #}
            <a data-bind="click: showUserTable.bind($data, true)" class="btn btn-primary"><span class="glyphicon glyphicon-arrow-left"></span> Go Back</a>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 table-container" data-bind="template: { name: 'template-articleTable', data: articleTable }"></div>
    </div>
    <!-- /ko-->
</script>
{# END: Admin options menu #}

{# START: Category - Modal Body #}
<script id="template-manageCategories" type="text/html">
    <div id="manage-categories" class="container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <ul class="nav nav-tabs nav-justified no-collapse" role="tablist">
                    <li role="presentation" class="active"><a data-bind="click: addCategory" href="#addCategory" aria-controls="addCategory" role="tab" data-toggle="tab">Add</a></li>
                    <li role="presentation"><a data-bind="click: editCategory" href="#editCategory" aria-controls="editCategory" role="tab" data-toggle="tab">Edit</a></li>
                    <li role="presentation"><a data-bind="click: deleteCategory" href="#deleteCategory" aria-controls="deleteCategory" role="tab" data-toggle="tab">Delete</a></li>
                </ul>
                {# START: Add/Edit/Delete Category forms #}
                <div class="tab-content">
                    {# Add category #}
                    <div role="tabpanel" class="tab-pane active" id="addCategory">
                        {{ render_form(get_form('AddCategory'), { '_action': url_for('user.add_category') }, default_databind=false) }}
                    </div>
                    {# Edit category #}
                    <div role="tabpanel" class="tab-pane" id="editCategory">
                        {{ render_form(get_form('EditCategory'), { '_action': url_for('user.edit_category'), 'id': {'data-bind': "value: selectedCategoryId"}, 'category': defaultCategorySelect, 'name': {'data-bind': "value: selectedCategory() ? selectedCategory() : '' "} }, default_databind=false) }}
                    </div>
                    {# Delete category #}
                    <div role="tabpanel" class="tab-pane" id="deleteCategory">
                        {{ render_form(get_form('DeleteCategory'), { '_action': url_for('user.delete_category'), 'id': {'data-bind': 'value: selectedCategoryId'}, 'category': defaultCategorySelect }, default_databind=false) }}
                    </div>
                </div>
                {# END: Add/Edit/Delete Category forms #}
            </div>
        </div>
    </div>
</script>
{# END: Category Modal - Modal Body #}

{# START: Edit Avatar - Modal Body #}
<script id="template-editAvatar" type="text/html">
    <div id="form-avatar" class="container-fluid">
        <div class="row">
            <div class="col-xs-12">
                {{ render_form(get_form('UploadAvatar'), { '_action': url_for('user.upload'), '_enctype': 'multipart/form-data' }, default_databind=false) }}
            </div>
            <div class="col-md-8">
                <h3 class="text-center">Canvas</h3>
                <div class="avatar-wrapper"><img data-bind="attr: { src: originalImage }" src="" alt="avatar" /></div>
            </div>
            <div class="col-md-4">
                <h3 class="text-center">Preview</h3>
                <div class="avatar-preview preview-lg"></div>
                <div class="avatar-preview preview-md"></div>
            </div>
        </div>
    </div>
</script>
{# END: Edit Avatar - Modal Body #}

{# Edit Profile form #}
<script id="template-editProfile" type="template">
    {{ render_form(get_form('EditProfile'), { '_action': url_for('user.edit_profile'), }) }}
</script>

{# Delete User form #}
<script id="template-deleteUser" type="template">
    <p>Are you sure you want to delete user <strong class="text-danger-inverse" data-bind="text: username"></strong> permanently?</p>
    {{ render_form(get_form('DeleteUser'), { '_action': url_for('user.delete_user') }) }}
</script>

app/templates/user/profile.html
{% extends 'layout.html' %}

{% block metaTags -%}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropper/0.9.1/cropper.min.css"/>
{%- endblock %}
{# Set navbar links used in nav-links component #}
{% set json_response = result|tojson %}

{% block header %}
    <script> requirejs(['user-profile']); </script>
{% endblock %}

{% block bodyID %}page-profile{% endblock %}

{% block body %}
<section class="profile">
    <div class="container">
        <div class="row"><div class="col-xs-12 alert-box"></div></div>
        <div class="row row-table-md">
            <div class="col-xs-12 col-md-4">
                <div class="avatar-container lg"><img class="avatar-thumbnail-lg" data-bind="attr: { src: user.avatar }" src="" alt=""/></div>
                <div class="more-info">
                    <div class="username"></div>
                    <div class="settings">
                        <a data-bind="click: avatarModal.editAvatar" href="#">Edit Avatar</a>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-md-8 general-info-container">
                <table data-bind="with: profileTable" id="profile-table" class="table table-hover profile-table">
                    <thead>
                        <tr>
                            <th class="title">General Info</th>
                            <th class="text-right">
                                <a data-bind="click: modal.editProfile" class="btn-profile-edit">Edit</a>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th>Username</th>
                            <td data-bind="text: user.username"></td>
                        </tr>
                        <tr>
                            <th>Email</th>
                            <td data-bind="text: user.email"></td>
                        </tr>
                        <tr>
                            <th>First Name</th>
                            <td data-bind="text: user.firstName"></td>
                        </tr>
                        <tr>
                            <th>Last Name</th>
                            <td data-bind="text: user.lastName"></td>
                        </tr>
                        <tr>
                            <th>Date Joined</th>
                            <td data-bind="timeFromNow: user.dateJoined"></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>

<section class="published-articles">
    <div class="container">
        <!-- ko template: { name: 'template-adminOptions', if: user.isAdmin, data: admin } --><!-- /ko -->
        <div class="row row-table-sm">
            <div class="col-xs-12 col-sm-8">
                <h1 class="main-title">Published Tutorials</h1>
            </div>
            <div class="col-xs-12 col-sm-4 add-btn-container">
                <a data-bind="click: articleModal.addArticle" class="btn btn-primary"> Add Tutorial <span class="glyphicon glyphicon-plus-sign"></span></a>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 table-container" data-bind="template: { name: 'template-articleTable', data: articleTable }"></div>
        </div>
    </div>
</section>
{# add page templates #}
{% include 'user/profile-templates.html' %}
{% endblock %}