app/views/frontend.py
from datetime import datetime
import pprint
from sqlalchemy import type_coerce, Integer, or_
from sqlalchemy import DateTime, cast

from sqlalchemy.orm import aliased
from sqlalchemy.dialects.postgresql import array
from sqlalchemy.dialects.postgresql import ARRAY
from sqlalchemy.sql.expression import literal
from flask import Blueprint, render_template, request, redirect, url_for, flash, g, abort
from flask_login import current_user, login_user, logout_user, login_required

from app.extensions import db, login_manager
from app.utils import xhr_or_redirect, xhr_required, get_login_manager_data, xhr_or_template
from app.forms import LoginForm, RegisterForm, AddCommentForm, AddReplyForm, EditCommentForm, EditReplyForm
from app.models import User, Article, Category, Comment
from app.schemas import (
    frontend_article_view_serializer as article_view_serializer,
    frontend_index_view_serializer as index_view_serializer,
    frontend_category_articles_serializer as category_articles_serializer,
    user_info_serializer
)
# JSON schema views

frontend_bp = Blueprint('frontend', __name__)


@frontend_bp.route('/')
@xhr_or_template('frontend/index.html')
def index():
    # Create response using `IndexViewSchema`
    result = index_view_serializer.dump({
        'user': current_user,
        'loginManager': get_login_manager_data(),
        'navbar': {
            'categories': Category.query.order_by(Category.name).all()
        }
    }).data

    return {'status': 200, 'result': result}


@frontend_bp.route('/<category>/')
@xhr_or_template('frontend/articles.html')
def category_articles(category):
    category = Category.query.filter_by(name=category).first()
    # Check if exists
    if category is None:
        abort(404)
    # Create response using `CategoryArticlesViewSchema`
    result = category_articles_serializer.dump({
        'user': current_user,
        'category': category.name,
        'loginManager': get_login_manager_data(),
        'articles': category.articles.order_by(Article.dateCreated).all(),
        'navbar': {
            'categories': Category.query.order_by(Category.name).all()
        }
    }).data

    return {'status': 200, 'result': result}


@frontend_bp.route('/<category>/<int:articleId>/<title>')
@xhr_or_template('frontend/article.html')
def article(category, articleId, title):
    article = Article.query.get(articleId)
    # Check if article exists
    if not article:
        abort(404)
    # redirect if the category or title doesn't match the article
    if article.title != title or category != article.category.name:
        return redirect(url_for('.article', category=article.category.name, articleId=article.id, title=article.title))

    comments = get_comments(articleId)
    # Create response using `ArticleViewSchema`
    result = article_view_serializer.dump({
        'user': current_user,
        'article': article,
        'comments': comments,
        'loginManager': get_login_manager_data(),
        'navbar': {
            'categories': Category.query.order_by(Category.name).all()
        }
    }).data
    return {'status': 200, 'result': result}



@frontend_bp.route('/add/comment', methods=['POST'])
@login_required
@xhr_required
def add_comment():
    form = AddCommentForm(request.form)
    # validate the form
    if form.validate_on_submit():
        comment = Comment(userId=current_user.id, **form.data)
        db.session.add(comment)
        db.session.commit()
        result = {
            'comments': get_comments(comment.articleId)
        }
        result, error = article_view_serializer.dump(result)
        return {'status': 200, 'result': result}
    else:
        flash(form.errors, 'form-error')
        return {'status': 400}

@frontend_bp.route('/add/reply', methods=['POST'])
@login_required
@xhr_required
def add_reply():
    form = AddReplyForm(request.form)
    # validate the form
    if form.validate_on_submit():
        recipient = Comment.query.get(form.parentId.data)
        # Make sure the recipient isn't a deleted user
        if recipient.user is None:
            flash("You can't reply to a non-existing user.", 'danger')
            return {'status': 400}
        comment = Comment(userId=current_user.id, **form.data)
        db.session.add(comment)
        db.session.commit()
        result = {
            'comments': get_comments(comment.articleId)
        }
        result, error = article_view_serializer.dump(result)
        return {'status': 200, 'result': result}
    else:
        flash(form.errors, 'form-error')
        return {'status': 400}


@frontend_bp.route('/edit/comment', methods=['POST'])
@login_required
@xhr_required
def edit_comment():
    # find out the form type
    if request.form.get('subject', None) is None:
        form = EditReplyForm(request.form)
    else:
        form = EditCommentForm(request.form)

    # validate the form
    if form.validate_on_submit():

        comment = Comment.query.filter_by(id=form.id.data).first()
        if comment is None:
            flash('No comment found.')
            return {'success': 0, 'status': 401}
        if comment.userId != current_user.id:
            flash('You do not have permission to edit this comment.')
            return {'success': 0, 'status': 401}

        comment.populate_from_form(form)
        comment.lastModified = datetime.utcnow()
        db.session.commit()
        result = {
            'comments': get_comments(comment.articleId)
        }
        result, error = article_view_serializer.dump(result)
        return {'status': 200, 'result': result}
    else:
        flash(form.errors, 'form-error')
        return {'status': 401}


# @frontend_bp.route('/mail/')
# def send_mail():
#     msg = Message('Hello its luiz :)',
#                   body='this is an email. lol',
#                   recipients=['larantessa@icloud.com'])
#     mail.send(msg)
#     return redirect(url_for('frontend.index'))


@frontend_bp.route('/login/', methods=['POST'])
@xhr_required
def login():
    if g.user and current_user.is_authenticated():
        flash('You are already logged in.', 'warning')
        return {'status': 400}

    form = LoginForm(request.form, prefix='l')
    if form.validate_on_submit():
        emailOrUsername = form.email.data
        if '@' in emailOrUsername:
            user = User.query.filter(User.email_insensitive == emailOrUsername).first()
        else:
            user = User.query.filter(User.username_insensitive == emailOrUsername).first()

        password = form.password.data
        if not user or not user.check_password(password):
            flash('Invalid email or password. Please try again.', 'danger')
            return {'status': 400}
        else:
            login_user(user)
            flash('You have successfully logged in.', 'success')
            result = {'user': user_info_serializer.dump(user).data}
            return {'status': 200, 'result': result}

    flash(form.errors, 'form-error')
    return {'status': 400}


@frontend_bp.route('/register/', methods=['POST'])
@xhr_required
def register():
    if g.user and current_user.is_authenticated():
        flash('You are currently logged in as ' + current_user.username + '. If this isn\'t you please logout.',
              'warning')
        return redirect(url_for('frontend.index'))

    form = RegisterForm(request.form, prefix='r')
    if form.validate_on_submit():
        # register and login user
        user = User(
            username=form.username.data,
            email=form.email.data,
            pwdhash=form.password.data)
        db.session.add(user)
        db.session.commit()
        login_user(user)
        flash('You have successfully registered. <br> You are currently logged in as <strong>' + user.username + '</strong>.', 'success')
        return {'status': 200, 'result': {'user': user_info_serializer.dump(user).data}}
    else:
        flash(form.errors, 'form-error')
        return {'status': 400}


@frontend_bp.route('/logout/', methods=['GET', 'POST'])
@xhr_or_redirect('frontend.index')
def logout():
    if not current_user.is_authenticated():
        flash('You must be logged in to logout...', 'warning')
        return {'status': 401, 'success': 0}
    logout_user()
    flash('You have successfully logged out.', 'success')
    return {'status': 200}


@login_manager.user_loader
def load_user(id):
    return User.query.get(int(id))


@login_manager.unauthorized_handler
@xhr_or_redirect('frontend.index')
def unauthorized():
    flash('You are not logged in.', 'danger')
    return {'status': 401}

def get_comments(articleId):
    # TODO: Test if using 2 CTEs is faster than 1. Revert back to 1 CTE if it isn't :/
    cte1 = db.session.query(Comment,
                            array([Comment.id]).label('path'),
                            literal(0, type_=Integer).label('depth')
                            ) \
        .filter_by(articleId=articleId, parentId=None).cte(name='cte', recursive=True)
    # Get all comments by article id and save it to a cte
    cte2 = db.session.query(Comment) \
        .filter_by(articleId=articleId).cte(name='cte2', recursive=False)

    c1_alias = aliased(cte1, name='c1')
    c2_alias = aliased(cte2, name='c2')

    cte1 = cte1.union_all(
        db.session.query(c2_alias,
                         c1_alias.c.path + array([c2_alias.c.id]).label('path'),
                         c1_alias.c.depth + literal(1, type_=Integer).label('depth'))
            .join(c1_alias, c2_alias.c.parentId == c1_alias.c.id))

    result = db.session.query(Comment,
                              type_coerce(cte1.c.path, ARRAY(Integer, as_tuple=True)),
                              cte1.c.depth
                              ). \
        select_entity_from(cte1).order_by('path').all()
    comments = []
    for comment, path, depth in result:
        comments.append(comment)
    return comments

app/templates/macros/alert-messages.html
{% macro alert_messages(messages) -%}
    {% for category, message in messages -%}
    <div class="alert-messages">
        <div class="alert alert-{{ category }}">
            <a href="#" class="close" data-dismiss="alert">&times;</a>
            {% if message is mapping %}
            <ul class="nav">
                {% for key, value in message.items() %}
                <li><strong>{{ key }}</strong>: {{ value|join(' ') }}</li>
                {% endfor %}
            </ul>
            {% else %}
                {{ message }}
            {% endif %}
        </div>
    </div>
    {%- endfor %}
{%- endmacro %}

app/templates/macros/form-components.html
{% macro render_checkbox_field(field) -%}
    <div class="checkbox">
        <label>{{ field(type='checkbox', **kwargs) }} {{ field.label }}</label>
    </div>
{%- endmacro %}

{% macro render_radio_field(field) -%}
    {% for value, label, _ in field.iter_choices() %}
        <div class="radio">
            <label>
                <input type="radio" name="{{ field.id }}" id="{{ field.id }}" value="{{ value }}">{{ label }}
            </label>
        </div>
    {% endfor %}
{%- endmacro %}

{% macro render_field(field, attributes=None) -%}
    {% set attributes = attributes|default({}, true) %}
    <div class="form-group">
        {% if field.widget.input_type != 'hidden' %}
            {{ field.label(class_='control-label') }}
        {% endif %}
        {{ field(class_='form-control', **attributes) }}
    </div>
{%- endmacro -%}

{%- macro render_input_group(field, attributes=None) -%}
    {% set attributes = attributes|default({}, true) %}
    {# set size options: lg sm or leave blank for medium which has no css class #}
    {% set size = attributes.pop('_size', '') %}
    {% if size != '' -%} {% set size = 'input-group-' + size  -%} {% endif -%}

    <div class="form-group">
    {%- if field.widget.input_type == 'hidden' -%}
        {{ field(**attributes) }}
    {% else -%}
        <label class="control-label sr-only">{{ field.label.text }}</label>
        <div class="input-group {{ size }}">
          <span class="input-group-addon">{{ attributes.pop('placeholder', field.label.text) }}</span>
          {{ field(class_='form-control', **attributes) }}
        </div>
    {% endif -%}
    </div>
{% endmacro -%}

{%- macro render_form(form, options, default_databind=true) -%}

    {# Get which type of bootstrap field to render #}
    {% set render = render_input_group if options.get('_fieldType', '') == 'input-group' else render_field %}

    <form enctype="{{ options.get('_enctype', 'application/x-www-form-urlencoded') }}" method="{{ options.get('_method', 'POST') }}" action="{{ options.get('_action', '') }}">
        {%- for field in form -%}
        {# Ignore csrf token fields since we will provide it on ajax requests #}
        {% if field.type != 'CSRFTokenField' -%}
                {% set fieldOptions = options.get(field.id, {}) %}
                {% if not fieldOptions.has_key('data-bind') and default_databind %}
                    {{ fieldOptions.update({'data-bind': 'value: form' + field.id[0:1:].capitalize() + field.id[1::]} )|default('', true) }}
                {% endif %}
                {{ render(field, fieldOptions) }}
        {% endif -%}

        {%- endfor %}
    </form>
{%- endmacro -%}

app/templates/macros/login-form.html
{%- macro render_login_form() -%}

{%- from 'macros/form-components.html' import render_field -%}
{%- from 'macros/social-buttons.html' import get_social_buttons -%}

{%- set registerForm = get_form('Register', prefix='r') -%}
{%- set loginForm = get_form('Login', prefix='l') -%}
{%- set social_buttons = get_social_buttons([ {'google-plus':'#'}, {'github':'#'}, {'facebook':'#'}], data_bind='click: oAuthLogin') -%}
{#<div data-bind="fadeVisible: " style="display: none;" id="login-form-container" class="nav-tabs-container">#}
<div id="login-form-container" class="nav-tabs-container">
  <!-- TAB NAVIGATION -->
  <ul id="form-tabs" class="nav nav-tabs nav-justified no-collapse" role="tablist">
      <li class="active"><a href="#tab-register" role="tab" data-toggle="tab">Register</a></li>
      <li><a href="#tab-login" role="tab" data-toggle="tab">Login</a></li>
  </ul>
  <!-- TAB CONTENT -->
  <div class="tab-content">
      <div class="active tab-pane fade in" id="tab-register">
          <form data-prefix="{{ registerForm._prefix }}" action="{{ url_for('frontend.register') }}" method="post" role="form">
              <div class="mobile-popover"></div>
              {% for field in registerForm if field.widget.input_type != 'hidden' -%}
                      {{ render_field(field, label_class='sr-only', placeholder=field.label.text) }}
              {% endfor %}
              <button type="submit" class="btn btn-block btn-lg btn-danger">Get Started</button>
          </form>
          <div class="social-media">
              <p class="info">Or register with:</p>
              <p class="text-justify-full">
                  {{ social_buttons }}
              </p>
          </div>
      </div>
      <div class="tab-pane fade" id="tab-login">
          <form data-prefix="{{ loginForm._prefix }}" action="{{ url_for('frontend.login') }}" method="post" role="form">
              {% for field in loginForm if field.widget.input_type != 'hidden' -%}
                      {{ render_field(field, label_class='sr-only', placeholder=field.label.text) }}
              {% endfor %}
              <button type="submit" class="btn btn-block btn-lg btn-danger">Login</button>
          </form>
          <div class="social-media">
              <p class="info">Or login with:</p>
              <p class="text-justify-full">
                  {{ social_buttons }}
              </p>
          </div>
      </div>
  </div>
</div>
{%- endmacro -%}

app/templates/macros/social-buttons.html
{% macro get_social_buttons(providers, data_bind='') -%}
    {% for provider in providers %}
        {% for name, url in provider.items() %}
        <a  data-bind="{{ data_bind }}" data-provider="{{ name }}" class="azm-{{ name }} btn-square hvr-grow" href="{{ url }}"><i class="fa fa-{{ name }}"> </i></a>
        {% endfor %}
    {%- endfor -%}
{%- endmacro %}